=== Floche01/HealthCareApp/HalthCare/wineStore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <element name="list">
    <complexType>
      <sequence>
        <element name="wine" minOccurs="0" maxOccurs="unbounded">
          <complexType>
            <sequence>
              <element name="name" type="string"/>
              <element name="type" type="string"/>
              <element name="country">
                <simpleType>
                  <restriction base="string">
                    <enumeration value="France"/>
                    <enumeration value="Italy"/>
                    <enumeration value="Spain"/>
                    <enumeration value="Chile"/>
                    <enumeration value="Argentina"/>
                    <enumeration value="United States"/>
                  </restriction>
                </simpleType>
              </element>
              <element name="grape" type="string"/>
              <element name="year">
                <simpleType>
                  <restriction base="integer">
                    <minInclusive value="1900"/>
                    <maxInclusive value="2019"/>
                  </restriction>
                </simpleType>
              </element>
              <element name="price">
                <simpleType>
                  <restriction base="decimal">
                    <minExclusive value="0.0"/>
                  </restriction>
                </simpleType>
              </element>
              <element name="imported" type="boolean">
              </element>
            </sequence>
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>
</schema>

=== Floche01/HealthCareApp/HalthCare/wineStore.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xsi:noNamespaceSchemaLocation="wineStore.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <wine>
    <name>Il Bastardo</name>
    <type>red</type>
    <country>Italy</country>
    <grape>Sangiovese</grape>
    <year>2015</year>
    <price>19.99</price>
    <imported>true</imported>
  </wine>
  <wine>
    <name>Atardi el tempranillo</name>
    <type>red</type>
    <country>Spain</country>
    <grape>Grenache</grape>
    <year>2014</year>
    <price>31.50</price>
    <imported>true</imported>
  </wine>
  <wine>
    <name>Cune Monopole</name>
    <type>white</type>
    <country>Spain</country>
    <grape>Macabeo</grape>
    <year>2017</year>
    <price>201.98</price>
    <imported>true</imported>
  </wine>
  <wine>
    <name>Chanteau de Landiras</name>
    <type>red</type>
    <country>France</country>
    <grape>Bordeaux</grape>
    <year>2009</year>
    <price>54.99</price>
    <imported>true</imported>
  </wine>
  <wine>
    <name>Cakebread</name>
    <type>white</type>
    <country>United States</country>
    <grape>Sauvignon blanc</grape>
    <year>2016</year>
    <price>78.99</price>
    <imported>false</imported>
  </wine>
</list>
